import { Inter } from "next/font/google";
import "./globals.css";
import styles from '@/app/layout.module.css'
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/ThemeProvider";
import { LocaleProvider } from "@/components/LocaleProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    // <html lang="en">
    <html>
      <body className={inter.className + ' ' + styles.body}>
        <LocaleProvider>
          <ThemeProvider>
          <Header/>
        <main className={styles.main}>
          {children}
        </main>
        <Footer/>
        </ThemeProvider>
        </LocaleProvider>
        
        
      </body>
    </html>
  );
  
  // return (
  //   <html lang="en">
  //     <body className={inter.className}>{children}</body>
  //   </html>
  // );
}
